name: qixer_seller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.4.3 <4.0.0'

dependency_overrides:
  intl: ^0.18.0
  pin_code_fields: ^8.0.1

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  file_picker: ^5.2.2
  firebase_core: ^1.15.0
  fl_chart: ^0.68.0
  flutter_inappwebview: ^5.7.2
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^9.0.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html_core: ^0.9.0+2
  fluttertoast: ^8.0.9
  flutterwave_standard: ^1.0.6
  flutterzilla_fixed_grid: ^0.0.4
  http_auth: ^1.0.1
  image_picker: ^0.8.5
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  # modal_bottom_sheet: ^3.0.0-pre
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  pusher_beams: ^1.1.1
  pusher_channels_flutter: ^2.0.1
  razorpay_flutter: ^1.3.0
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.0.15
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^12.0.0
  connectivity_plus: ^5.0.2
  flutter_widget_from_html: ^0.9.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
