var appStringsEn = {
  "Welcome back! Login": "Welcome back! Login",
  "Email or username": "Email or username",
  'Please enter your email': 'Please enter your email',
  "Email": "Email",
  "Password": "Password",
  'Please enter your password': 'Please enter your password',
  'Enter password': 'Enter password',
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  'Do not have an account': 'Do not have an account',
  'Register': 'Register',
  "Reset password": "Reset password",
  "Enter the email you used to create account and we will send instruction for resetting password":
      "Enter the email you used to create account and we will send instruction for resetting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  'Enter the 4 digit code we sent to to your email in order to reset password':
      'Enter the 4 digit code we sent to to your email in order to reset password',
  'Did not receive?': 'Did not receive?',
  'Send again': 'Send again',
  "Enter new password": "Enter new password",
  "Your new password be different from previously used passwords":
      "Your new password be different from previously used passwords",
  'New password': 'New password',
  "Repeat new password": "Repeat new password",
  'Please retype your password': 'Please retype your password',
  'Retype new password': 'Retype new password',
  "Change password": "Change password",
  "Choose country": "Choose country",
  "Choose states": "Choose states",
  "Choose area": "Choose area",
  'Please enter your full name': 'Please enter your full name',
  "Full name": "Full name",
  "Enter your full name": "Enter your full name",
  "Username": "Username",
  'Please enter your username': 'Please enter your username',
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  'Enter the 4 digit code we sent to to your email in order verify your email':
      'Enter the 4 digit code we sent to to your email in order verify your email',
  "Phone": "Phone",
  "Confirm Password": "Confirm Password",
  'Retype password': 'Retype password',
  'Have an account?': 'Have an account?',
  'Sign in': 'Sign in',
  'Phone Number': 'Phone Number',
  'Enter phone number': 'Enter phone number',
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  'You must agree with the terms and conditions to register':
      'You must agree with the terms and conditions to register',
  'Password did not match': 'Password did not match',
  'Password must be at least 6 characters':
      'Password must be at least 6 characters',
  'Already have an account?': 'Already have an account?',
  "See all": "See all",
  "Press again to exit": "Press again to exit",
  'Welcome!': 'Welcome!',
  'Order Pending': 'Order Pending',
  'Order Completed': 'Order Completed',
  'Total Withdraw': 'Total Withdraw',
  'Remaining Balance': 'Remaining Balance',
  'Recent Orders': 'Recent Orders',
  "Order ID:": "Order ID:",
  "House Cleaning Service": "House Cleaning Service",
  "Repairing Services": "Repairing Services",
  "Home Shifting Service": "Home Shifting Service",
  'Online': 'Online',
  'Date': 'Date',
  'Schedule': 'Schedule',
  'Billed': 'Billed',
  'Ordered service': 'Ordered service',
  "Service ID:": "Service ID:",
  'Buyer Details': 'Buyer Details',
  'Name': 'Name',
  'Post code': 'Post code',
  'Address': 'Address',
  'Date & Schedule': 'Date & Schedule',
  'Amount Details': 'Amount Details',
  'Package fee': 'Package fee',
  'Extra service': 'Extra service',
  'Subtotal': 'Subtotal',
  'Tax': 'Tax',
  'Total': 'Total',
  'Payment status': 'Payment status',
  'Order Status': 'Order Status',
  "No details found": "No details found",
  'Payout history': 'Payout history',
  'Withdraw': 'Withdraw',
  'Payout Request Details': 'Payout Request Details',
  'ID': 'ID',
  'Amount': 'Amount',
  'Payment Gateway': 'Payment Gateway',
  'Request Date': 'Request Date',
  'Seller Note': 'Seller Note',
  'Admin Note': 'Admin Note',
  'Status': 'Status',
  'Payout Receipt': 'Payout Receipt',
  'Request date': 'Request date',
  'View': 'View',
  "Gateway": "Gateway",
  'Please enter an amount': 'Please enter an amount',
  "Note": "Note",
  'You can make a request only if your remaining balance in a range set by the site admin. Like admin set minimum request amount':
      'You can make a request only if your remaining balance in a range set by the site admin. Like admin set minimum request amount',
  "and maximum request amount": "and maximum request amount",
  "then you can request a payment between":
      "then you can request a payment between",
  "to": "to",
  'Please enter a note': 'Please enter a note',
  "Choose Reason": "Choose Reason",
  "Short description": "Short description",
  'description': 'description',
  "Deactivate": "Deactivate",
  'Please enter a description': 'Please enter a description',
  "Enter current password": "Enter current password",
  'Enter your current password': 'Enter your current password',
  'Please wait while the profile is updating':
      'Please wait while the profile is updating',
  'Please enter post code': 'Please enter post code',
  "Enter your post code": "Enter your post code",
  "Your Address": "Your Address",
  "About": "About",
  'Save': 'Save',
  'Address field is required': 'Address field is required',
  'Phone field is required': 'Phone field is required',
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  'City': 'City',
  'Area': 'Area',
  'Country': 'Country',
  'Post Code': 'Post Code',
  'Edit Profile': 'Edit Profile',
  'Address document image': 'Address document image',
  'Choose address images': 'Choose address images',
  'NID document image': 'NID document image',
  'Choose NID images': 'Choose NID images',
  'Upload': 'Upload',
  "Account verified": "Account verified",
  "Open": "Open",
  "Close": "Close",
  'Ticket ID:': 'Ticket ID:',
  'Chat': 'Chat',
  "Write message...": "Write message...",
  'Please write a message first': 'Please write a message first',
  "Make payment status complete?": "Make payment status complete?",
  "Make payment status complete": "Make payment status complete",
  "Welcome": "Welcome",
  "Make sure you repeated new password correctly":
      "Make sure you repeated new password correctly",
  "Password changed successfully": "Password changed successfully",
  "Something went wrong": "Something went wrong",
  "Please turn on your internet connection":
      "Please turn on your internet connection",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "Your entered the otp correctly but something went wrong. Please try again later",
  "Otp didn't match": "Otp didn't match",
  "Otp is null": "Otp is null",
  "Invalid Email or Password": "Invalid Email or Password",
  "Password didn't match": "Password didn't match",
  "Registration successful": "Registration successful",
  "Otp send failed": "Otp send failed",
  "Only zip file is supported": "Only zip file is supported",
  "Please check your internet connection":
      "Please check your internet connection",
  "Job message from": "Job message from",
  "Successfully applied": "Successfully applied",
  "New job request from": "New job request from",
  "New chat message": "New chat message",
  "Make sure you have added include, additional, benefits, faq":
      "Make sure you have added include, additional, benefits, faq",
  "Service attribute added, Refreshing list....":
      "Service attribute added, Refreshing list....",
  "Attribute deleted": "Attribute deleted",
  "You must select a main image": "You must select a main image",
  "Service created": "Service created",
  "Service updated. Refreshing list": "Service updated. Refreshing list",
  "Service attribute updated": "Service attribute updated",
  "Service deleted. Refreshing list.....":
      "Service deleted. Refreshing list.....",
  "Error filling out fields": "Error filling out fields",
  "Report submitted": "Report submitted",
  "Select Country": "Select Country",
  "Select State": "Select State",
  "Select Area": "Select Area",
  "Account deactivated, Logging out": "Account deactivated, Logging out",
  "Extra added": "Extra added",
  "Successfully deleted": "Successfully deleted",
  "requested to mark this order complete.":
      "requested to mark this order complete.",
  "Order id": "Order id",
  "Order cancelled": "Order cancelled",
  "Profile updated successfully": "Profile updated successfully",
  "You must upload both Address and NID document image":
      "You must upload both Address and NID document image",
  "Document Submitted": "Document Submitted",
  "Subscription renewed successfully": "Subscription renewed successfully",
  "Wallet deposit success": "Wallet deposit success",
  "You must enter an amount": "You must enter an amount",
  "Please enter a valid amount": "Please enter a valid amount",
  "Ticket created successfully": "Ticket created successfully",
  "Sign up": "Sign up",
  "subscription": "subscription",
  "Expire date": "Expire date",
  "All orders": "All orders",
  "Support ticket": "Support ticket",
  "Subscriptions": "Subscriptions",
  "You don't have permission to access this feature":
      "You don't have permission to access this feature",
  "New jobs": "New jobs",
  "Applied jobs": "Applied jobs",
  "Wallet": "Wallet",
  "Profile": "Profile",
  "Profile verify": "Profile verify",
  "Services": "Services",
  "My Report list": "My Report list",
  "Deactivate account": "Deactivate account",
  "Logout": "Logout",
  "All Orders": "All Orders",
  "You can not cancel this order": "You can not cancel this order",
  "Cancel order": "Cancel order",
  "Report to admin": "Report to admin",
  "Order Details": "Order Details",
  "Payment method": "Payment method",
  "Order status": "Order status",
  "Request buyer to mark this order complete":
      "Request buyer to mark this order complete",
  "Decline history": "Decline history",
  "Decline reason": "Decline reason",
  "Buyer details": "Buyer details",
  "Add extra": "Add extra",
  "Ticket ID": "Ticket ID",
  "Start date": "Start date",
  "No history found": "No history found",
  "Subscription details": "Subscription details",
  "Note: Pending connect will be added to available connect only if the payment status is completed":
      "Note: Pending connect will be added to available connect only if the payment status is completed",
  "Type": "Type",
  "Connect details": "Connect details",
  "Available connect": "Available connect",
  "Pending connect": "Pending connect",
  "Payment details": "Payment details",
  "Payment gateway": "Payment gateway",
  "Renew Subscription": "Renew Subscription",
  "Payment": "Payment",
  "Total Payable": "Total Payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  "I agree with terms and conditions": "I agree with terms and conditions",
  "Budget": "Budget",
  "Pay & Confirm": "Pay & Confirm",
  "You must agree with the terms and conditions":
      "You must agree with the terms and conditions",
  "Buyer budget": "Buyer budget",
  "No new jobs found": "No new jobs found",
  "You didn't apply to any job": "You didn't apply to any job",
  "Your offer": "Your offer",
  "View details": "View details",
  "Conversation": "Conversation",
  "Deadline": "Deadline",
  "Apply": "Apply",
  "Edit profile": "Edit profile",
  "Verify": "Verify",
  "You don't have any active conversation":
      "You don't have any active conversation",
  "Balance": "Balance",
  "History": "History",
  "Payment Status": "Payment Status",
  "Starts from": "Starts from",
  "On/Off": "On/Off",
  "No service found": "No service found",
  "Reports": "Reports",
  "Report id": "Report id",
  "Chat admin": "Chat admin",
  "No Report": "No Report",
  "Change Password": "Change Password",
  "Vacation": "Vacation",
  "Personal reason": "Personal reason",
  "Queue": "Queue",
  "Completed": "Completed",
  "Cancelled": "Cancelled",
  "Show attributes": "Show attributes",
  "Edit attributes": "Edit attributes",
  "Add attributes": "Add attributes",
  "Delete service": "Delete service",
  "Edit service": "Edit service",
  "Create": "Create",
  "Conversations": "Conversations",
  "Search": "Search",
  "Deposit Amount": "Deposit Amount",
  "Enter deposit amount": "Enter deposit amount",
  "Deposit from current balance": "Deposit from current balance",
  "My services": "My services",
  "Create Service": "Create Service",
  "Is available to all cities and area": "Is available to all cities and area",
  "Category": "Category",
  "Sub category": "Sub category",
  "Child category": "Child category",
  "Select child category": "Select child category",
  "Select Subcategory": "Select Subcategory",
  "Select Category": "Select Category",
  "Title": "Title",
  "Please enter a title": "Please enter a title",
  "Video URL": "Video URL",
  "Youtube embed code": "Youtube embed code",
  "Description": "Description",
  "Upload main image": "Upload main image",
  "Upload gallery image": "Upload gallery image",
  "You must enter a title and description":
      "You must enter a title and description",
  "Description must be at least 150 characters":
      "Description must be at least 150 characters",
  "Next": "Next",
  "Online service": "Online service",
  "What is Included In This Package": "What is Included In This Package",
  "Enter title": "Enter title",
  "Price": "Price",
  "Enter price": "Enter price",
  "Please enter a price": "Please enter a price",
  "Add Additional Services": "Add Additional Services",
  "Unit price": "Unit price",
  "Quantity": "Quantity",
  "Enter quantity": "Enter quantity",
  "Please fill out all fields": "Please fill out all fields",
  "Benefit Of This Package": "Benefit Of This Package",
  "Type here": "Type here",
  "Please type something first": "Please type something first",
  "Faqs": "Faqs",
  "Faq title": "Faq title",
  "Faq answer": "Faq answer",
  "Enter answer": "Enter answer",
  "Service attributes": "Service attributes",
  "Include Service Attributes": "Include Service Attributes",
  "No include service found": "No include service found",
  "Additional Service Attributes ": "Additional Service Attributes ",
  "No additional service found": "No additional service found",
  "Service Benefit": "Service Benefit",
  "No service benefit found": "No service benefit found",
  "Edit Service": "Edit Service",
  "Active": 'Active',
  "Pending": 'Pending',
  "pending": 'pending',
  "Delivered": 'Delivered',
  "complete": 'complete',
  "Unknown": 'Unknown',
  "hello": "hello",
  "Skip": "Skip",
  "Continue": "Continue",
  "Delete": "Delete",
  "Cancel": "Cancel",
  "Are you sure?": "Are you sure?",
  "Are you sure": "Are you sure",
  "Schedules": "Schedules",
  "Create Day": "Create Day",
  "Days": "Days",
  "Choose day": "Choose day",
  "Create Schedule": "Create Schedule",
  "eg: 10:00Am - 11:00PM, this schedule time will show in frontend, when anyone want to book your service, they will select this schedule time made by you":
      "eg: 10:00Am - 11:00PM, this schedule time will show in frontend, when anyone want to book your service, they will select this schedule time made by you",
  "No days found": "No days found",
  "Add Day": "Add Day",
  "Select a day to save": "Select a day to save",
  "Day created successfully": "Day created successfully",
  "Creating day failed": "Creating day failed",
  "Day fetching failed": "Day fetching failed",
  "Request timeout": "Request timeout",
  "Fetching days failed": "Fetching days failed",
  "Add this schedule time for all days.":
      "Add this schedule time for all days.",
  "Schedule fetching failed": "Schedule fetching failed",
  "Next page loading failed": "Next page loading failed",
  "Select a day to continue": "Select a day to continue",
  "Write schedule to continue": "Write schedule to continue",
  "Creating schedule failed": "Creating schedule failed",
  "Schedule deleted successfully": "Schedule deleted successfully",
  "Schedule delete failed": "Schedule delete failed",
  "Deleting day failed": "Deleting day failed",
  "Day deleted successfully": "Day deleted successfully",
  "No more Data": "No more Data",
  "Release to load more": "Release to load more",
  "Load Failed": "Load Failed",
  "Schedule updated successfully": "Schedule updated successfully",
  "Updating schedule failed": "Updating schedule failed",
  "Schedule created successfully": "Schedule created successfully",
  "Update Schedule": "Update Schedule",
  "Sat": "Sab",
  "Sun": "Dom",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mie",
  "Fri": "Vie",
  "Thu": "Jue",
  "Support tickets": "Support tickets",
  "Priority": "Priority",
  "Order number": "Order number",
  "Success": "Success",
  "Order extra accepted": "Order extra accepted",
  "Hired successfully": "Hired successfully",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "Enter schedule": "Enter schedule",
  "Add Schedule": "Add Schedule",
  "No schedules found": "No schedules found",
  "May": "May",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Sep",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Dic",
  "Jan": "Ene",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Abr",
  "What went wrong?": "What went wrong?",
  "Write the issue": "Write the issue",
  "Submit Report": "Submit Report",
  "You must write a report to submit": "You must write a report to submit",
  "Report": "Report",
  "Yes": "Yes",
  "Chat Payment details": "Chat Payment details",
  "Please indicate your payment account":
      "Please indicate your payment account",
  "Urgent": "Urgent",
  "High": "High",
  "Half": "Half",
  "Low": "Low",
  "open": "open",
  "Offer price": "Offer price",
  "Cover letter": "Cover letter",
  "You must enter a valid price": "You must enter a valid price",
  "Search country": "Search country",
  "Please enter a quantity": "Please enter a quantity",
  "Add": "Add",
  "requested to mark his order complete.":
      "requested to mark his order complete.",
  "You can not change order status due to payment status pending.":
      "You can not change order status due to payment status pending.",
  "Your request submitted. Buyer will complete your request after review.":
      "Your request submitted. Buyer will complete your request after review.",
  "requested new extra service.": "requested new extra service.",
  "has requested for extra service.": "has requested for extra service.",
  "You must enter a valid amount": "You must enter a valid amount",
  "Quantity must be an integer value": "Quantity must be an integer value",
  "Please enter ticket title": "Please enter ticket title",
  "Ticket title": "Ticket title",
  "Please explain your problem": "Please explain your problem",
  "Create ticket": "Create ticket",
  "Please enter order id": "Please enter order id",
  "Order Id": "Order Id",
  "Edit": "Edit",
  "Withdraw amount not less than": "Withdraw amount not less than",
  "Payout request success": "Payout request success",
  "manual payment": "manual payment",
  "Details": "Details",
  "Additional Service Attributes": "Additional Service Attributes",
  "Enter a valid amount": "Enter a valid amount",
  "No city found": "No city found",
  "Search state": "Search state",
  "Select City": "Select City",
  "No country found": "No country found",
  "No area found": "No area found",
  "Search area": "Search area",
  "Choose image": "Choose image",
  "declined your order extra request": "declined your order extra request",
  "Decline Success": "Decline Success",
  "Extra Service Not Found": "Low",
  "No date found": "No date found",
  "No Schedule Created": "No Schedule Created",
  "All jobs": "All jobs",
  "No jobs found": "No jobs found",
  "Please enter a valid password": "Please enter a valid password",
  "Delete account": "Delete account",
  "Invalid password": "Invalid password",
  "No payment history found": "No payment history found",
  "active": "active",
  "delivered": "delivered",
  "cancelled": "cancelled",
  "No order found": "No order found",
  "Order Not Found": "Order Not Found",
  "Support Ticket Created Success": "Support Ticket Created Success",
  "Login successful": "Login successful",
  "All": "All",
  "Create day to add schedule": "Create day to add schedule",
  "Order": "Order",
  "Message:": "Message:",
  "Your payment process will be terminated.":
      "Your payment process will be terminated.",
  "Payment cancelled!": "Payment cancelled!",
  "Payment failed!": "Payment failed!",
  "Payment has been expired.": "Payment has been expired.",
  "Payment has been cancelled.": "Payment has been cancelled.",
  "Cash on delivery is not available for subscription renew":
      "Cash on delivery is not available for subscription renew",
  "Pay by wallet is not available for wallet deposit":
      "Pay by wallet is not available for wallet deposit",
  "Job id": "Job id",
  "Privacy policy": "Privacy policy",
  "Terms & Conditions": "Terms & Conditions",
  "and": "and",
  "I agree to": "I agree to",
  "Applied": "Applied",
  "Job expired": "Job expired",
  "Hired": "Hired",
  "Language": "Language",
  "English": "English",
  "Arabic": "Arabic",
};
