var appStringsAr = {
  "Welcome back! Login": "مرحبا بعودتك! تسجيل الدخول",
  "Email or username": "البريد الإلكتروني أو اسم المستخدم",
  "Please enter your email": "يرجى إدخال بريدك الإلكتروني",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Please enter your password": "يرجى إدخال كلمة المرور",
  "Enter password": "أدخل كلمة المرور",
  "Remember me": "تذكرني",
  "Forgot Password?": "نسيت كلمة المرور؟",
  "Login": "تسجيل الدخول",
  "Do not have an account": "لا تملك حساباً",
  "Register": "تسجيل",
  "Reset password": "إعادة تعيين كلمة المرور",
  "Enter the email you used to create account and we will send instruction for resetting password": "أدخل البريد الإلكتروني الذي استخدمته لإنشاء الحساب وسنرسل تعليمات لإعادة تعيين كلمة المرور",
  "Enter Email": "أدخل البريد الإلكتروني",
  "Send Instructions": "إرسال التعليمات",
  "Enter the 4 digit code": "أدخل الرمز المكون من 4 أرقام",
  "Enter the 4 digit code we sent to to your email in order to reset password": "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني من أجل إعادة تعيين كلمة المرور",
  "Did not receive?": "لم تستلم؟",
  "Send again": "إرسال مرة أخرى",
  "Enter new password": "أدخل كلمة مرور جديدة",
  "Your new password be different from previously used passwords": "يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمات المرور السابقة",
  "New password": "كلمة مرور جديدة",
  "Repeat new password": "أعد إدخال كلمة المرور الجديدة",
  "Please retype your password": "يرجى إعادة كتابة كلمة المرور",
  "Retype new password": "أعد كتابة كلمة المرور الجديدة",
  "Change password": "تغيير كلمة المرور",
  "Choose country": "اختر البلد",
  "Choose states": "اختر الولايات",
  "Choose area": "اختر المنطقة",
  "Please enter your full name": "يرجى إدخال اسمك الكامل",
  "Full name": "الاسم الكامل",
  "Enter your full name": "أدخل اسمك الكامل",
  "Username": "اسم المستخدم",
  "Please enter your username": "يرجى إدخال اسم المستخدم",
  "Enter your username": "أدخل اسم المستخدم",
  "Enter your email": "أدخل بريدك الإلكتروني",
  "Enter the 4 digit code we sent to to your email in order verify your email": "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني للتحقق من بريدك الإلكتروني",
  "Phone": "الهاتف",
  "Confirm Password": "تأكيد كلمة المرور",
  "Retype password": "أعد كتابة كلمة المرور",
  "Have an account?": "هل لديك حساب؟",
  "Sign in": "تسجيل الدخول",
  "Phone Number": "رقم الهاتف",
  "Enter phone number": "أدخل رقم الهاتف",
  "I agree with the terms and conditions": "أوافق على الشروط والأحكام",
  "You must agree with the terms and conditions to register": "يجب عليك الموافقة على الشروط والأحكام للتسجيل",
  "Password did not match": "كلمة المرور غير متطابقة",
  "Password must be at least 6 characters": "يجب أن تكون كلمة المرور على الأقل 6 أحرف",
  "Already have an account?": "هل لديك حساب بالفعل؟",
  "See all": "عرض الكل",
  "Press again to exit": "اضغط مرة أخرى للخروج",
  "Welcome!": "أهلاً وسهلاً!",
  "Order Pending": "الطلب قيد الانتظار",
  "Order Completed": "الطلب مكتمل",
  "Total Withdraw": "إجمالي السحب",
  "Remaining Balance": "الرصيد المتبقي",
  "Recent Orders": "الطلبات الأخيرة",
  "Order ID:": "رقم الطلب:",
  "House Cleaning Service": "خدمة تنظيف المنازل",
  "Repairing Services": "خدمات الإصلاح",
  "Home Shifting Service": "خدمة نقل المنازل",
  "Online": "متصل",
  "Date": "التاريخ",
  "Schedule": "الجدول الزمني",
  "Billed": "فاتورة",
  "Ordered service": "الخدمة المطلوبة",
  "Service ID:": "رقم الخدمة:",
  "Buyer Details": "تفاصيل المشتري",
  "Name": "الاسم",
  "Post code": "الرمز البريدي",
  "Address": "العنوان",
  "Date & Schedule": "التاريخ والجدول الزمني",
  "Amount Details": "تفاصيل المبلغ",
  "Package fee": "رسوم الحزمة",
  "Extra service": "خدمة إضافية",
  "Subtotal": "المجموع الفرعي",
  "Tax": "الضريبة",
  "Total": "الإجمالي",
  "Payment status": "حالة الدفع",
  "Order Status": "حالة الطلب",
  "No details found": "لم يتم العثور على تفاصيل",
  "Payout history": "تاريخ السحب",
  "Withdraw": "سحب",
  "Payout Request Details": "تفاصيل طلب السحب",
  "ID": "رقم التعريف",
  "Amount": "المبلغ",
  "Payment Gateway": "بوابة الدفع",
  "Request Date": "تاريخ الطلب",
  "Seller Note": "ملاحظة البائع",
  "Admin Note": "ملاحظة المسؤول",
  "Status": "الحالة",
  "Payout Receipt": "إيصال السحب",
  "Request date": "تاريخ الطلب",
  "View": "عرض",
  "Gateway": "البوابة",
  "Please enter an amount": "يرجى إدخال مبلغ",
  "Note": "ملاحظة",
  "You can make a request only if your remaining balance in a range set by the site admin. Like admin set minimum request amount": "يمكنك تقديم طلب فقط إذا كان رصيدك المتبقي ضمن النطاق الذي حدده مسؤول الموقع. مثل حد أدنى لمبلغ الطلب",
  "and maximum request amount": "وحد أقصى لمبلغ الطلب",
  "then you can request a payment between": "ثم يمكنك طلب دفع بين",
  "to": "إلى",
  "Please enter a note": "يرجى إدخال ملاحظة",
  "Choose Reason": "اختر السبب",
  "Short description": "وصف قصير",
  "description": "الوصف",
  "Deactivate": "إلغاء التنشيط",
  "Please enter a description": "يرجى إدخال وصف",
  "Enter current password": "أدخل كلمة المرور الحالية",
  "Enter your current password": "أدخل كلمة مرورك الحالية",
  "Please wait while the profile is updating": "يرجى الانتظار بينما يتم تحديث الملف الشخصي",
  "Please enter post code": "يرجى إدخال الرمز البريدي",
  "Enter your post code": "أدخل الرمز البريدي الخاص بك",
  "Your Address": "عنوانك",
  "About": "حول",
  "Save": "حفظ",
  "Address field is required": "حقل العنوان مطلوب",
  "Phone field is required": "حقل الهاتف مطلوب",
  "Updating profile...It may take few seconds": "جاري تحديث الملف الشخصي... قد يستغرق بضع ثوانٍ",
  "City": "المدينة",
  "Area": "المنطقة",
  "Country": "البلد",
  "Post Code": "الرمز البريدي",
  "Edit Profile": "تعديل الملف الشخصي",
  "Address document image": "صورة مستند العنوان",
  "Choose address images": "اختر صور العنوان",
  "NID document image": "صورة مستند الهوية الوطنية",
  "Choose NID images": "اختر صور الهوية الوطنية",
  "Upload": "رفع",
  "Account verified": "تم التحقق من الحساب",
  "Open": "فتح",
  "Close": "إغلاق",
  "Ticket ID:": "رقم التذكرة:",
  "Chat": "الدردشة",
  "Write message...": "اكتب رسالة...",
  "Please write a message first": "يرجى كتابة رسالة أولاً",
  "Make payment status complete?": "هل تريد جعل حالة الدفع مكتملة؟",
  "Make payment status complete": "اجعل حالة الدفع مكتملة",
  "Welcome": "أهلاً وسهلاً",
  "Make sure you repeated new password correctly": "تأكد من أنك أعدت كتابة كلمة المرور الجديدة بشكل صحيح",
  "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Something went wrong": "حدث خطأ ما",
  "Please turn on your internet connection": "يرجى تشغيل اتصالك بالإنترنت",
  "Your entered the otp correctly but something went wrong. Please try again later": "أدخلت رمز التحقق بشكل صحيح ولكن حدث خطأ ما. يرجى المحاولة مرة أخرى لاحقاً",
  "Otp didn't match": "الرمز غير متطابق",
  "Otp is null": "الرمز فارغ",
  "Invalid Email or Password": "البريد الإلكتروني أو كلمة المرور",
  "Password didn't match": "كلمة المرور غير متطابقة",
  "Registration successful": "تم التسجيل بنجاح",
  "Otp send failed": "فشل إرسال رمز التحقق",
  "Only zip file is supported": "فقط ملفات zip مدعومة",
  "Please check your internet connection": "يرجى التحقق من اتصالك بالإنترنت",
  "Job message from": "رسالة وظيفة من",
  "Successfully applied": "تم التقديم بنجاح",
  "New job request from": "طلب وظيفة جديد من",
  "New chat message": "رسالة دردشة جديدة",
  "Make sure you have added include, additional, benefits, faq": "تأكد من أنك قد أضفت ما يتضمنه، الإضافات، الفوائد، الأسئلة الشائعة",
  "Service attribute added, Refreshing list....": "تمت إضافة سمة الخدمة، جارٍ تحديث القائمة....",
  "Attribute deleted": "تم حذف السمة",
  "You must select a main image": "يجب عليك اختيار صورة رئيسية",
  "Service created": "تم إنشاء الخدمة",
  "Service updated. Refreshing list": "تم تحديث الخدمة. جارٍ تحديث القائمة",
  "Service attribute updated": "تم تحديث سمة الخدمة",
  "Service deleted. Refreshing list.....": "تم حذف الخدمة. جارٍ تحديث القائمة.....",
  "Error filling out fields": "خطأ في ملء الحقول",
  "Report submitted": "تم تقديم التقرير",
  "Select Country": "اختر البلد",
  "Select State": "اختر الولاية",
  "Select Area": "اختر المنطقة",
  "Account deactivated, Logging out": "تم إلغاء تفعيل الحساب، جاري تسجيل الخروج",
  "Extra added": "تمت إضافة الإضافات",
  "Successfully deleted": "تم الحذف بنجاح",
  "requested to mark this order complete.": "طلبت وضع علامة على هذا الطلب كمنجز.",
  "Order id": "رقم الطلب",
  "Order cancelled": "تم إلغاء الطلب",
  "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
  "You must upload both Address and NID document image": "يجب عليك تحميل كل من صورة عنوانك وصورة بطاقة الهوية",
  "Document Submitted": "تم تقديم الوثيقة",
  "Subscription renewed successfully": "تم تجديد الاشتراك بنجاح",
  "Wallet deposit success": "تم إيداع الرصيد في المحفظة بنجاح",
  "You must enter an amount": "يجب عليك إدخال مبلغ",
  "Please enter a valid amount": "يرجى إدخال مبلغ صحيح",
  "Ticket created successfully": "تم إنشاء التذكرة بنجاح",
  "Sign up": "اشترك",
  "subscription": "الاشتراك",
  "Expire date": "تاريخ الانتهاء",
  "All orders": "جميع الطلبات",
  "Support ticket": "تذكرة دعم",
  "Subscriptions": "الاشتراكات",
  "You don't have permission to access this feature": "ليس لديك إذن للوصول إلى هذه الميزة",
  "New jobs": "وظائف جديدة",
  "Applied jobs": "الوظائف المقدمة",
  "Wallet": "المحفظة",
  "Profile": "الملف الشخصي",
  "Profile verify": "تحقق من الملف الشخصي",
  "Services": "الخدمات",
  "My Report list": "قائمة تقاريري",
  "Deactivate account": "إلغاء تفعيل الحساب",
  "Logout": "تسجيل الخروج",
  "All Orders": "جميع الطلبات",
  "You can not cancel this order": "لا يمكنك إلغاء هذا الطلب",
  "Cancel order": "إلغاء الطلب",
  "Report to admin": "تقرير إلى الإدارة",
  "Order Details": "تفاصيل الطلب",
  "Payment method": "طريقة الدفع",
  "Order status": "حالة الطلب",
  "Request buyer to mark this order complete": "طلب من المشتري وضع علامة على هذا الطلب كمنجز",
  "Decline history": "تاريخ الرفض",
  "Decline reason": "سبب الرفض",
  "Buyer details": "تفاصيل المشتري",
  "Add extra": "إضافة إضافات",
  "Ticket ID": "رقم التذكرة",
  "Start date": "تاريخ البدء",
  "No history found": "لم يتم العثور على تاريخ",
  "Subscription details": "تفاصيل الاشتراك",
  "Note: Pending connect will be added to available connect only if the payment status is completed": "ملاحظة: سيتم إضافة الاتصال المعلق إلى الاتصال المتاح فقط إذا كانت حالة الدفع مكتملة",
  "Type": "النوع",
  "Connect details": "تفاصيل الاتصال",
  "Available connect": "الاتصال المتاح",
  "Pending connect": "الاتصال المعلق",
  "Payment details": "تفاصيل الدفع",
  "Payment gateway": "بوابة الدفع",
  "Renew Subscription": "تجديد الاشتراك",
  "Payment": "الدفع",
  "Total Payable": "إجمالي المبلغ المستحق",
  "Choose payment method": "اختر طريقة الدفع",
  "Choose images": "اختر الصور",
  "I agree with terms and conditions": "أوافق على الشروط والأحكام",
  "Budget": "الميزانية",
  "Pay & Confirm": "ادفع و أكد",
  "You must agree with the terms and conditions": "يجب عليك الموافقة على الشروط والأحكام",
  "Buyer budget": "ميزانية المشتري",
  "No new jobs found": "لم يتم العثور على وظائف جديدة",
  "You didn't apply to any job": "لم تتقدم إلى أي وظيفة",
  "Your offer": "عرضك",
  "View details": "عرض التفاصيل",
  "Conversation": "المحادثة",
  "Deadline": "الموعد النهائي",
  "Apply": "تقديم الطلب",
  "Edit profile": "تعديل الملف الشخصي",
  "Verify": "تحقق",
  "You don't have any active conversation": "لا توجد لديك أي محادثات نشطة",
  "Balance": "الرصيد",
  "History": "التاريخ",
  "Payment Status": "حالة الدفع",
  "Starts from": "يبدأ من",
  "On/Off": "تشغيل/إيقاف",
  "No service found": "لم يتم العثور على خدمة",
  "Reports": "التقارير",
  "Report id": "رقم التقرير",
  "Chat admin": "دردشة مع الإدارة",
  "No Report": "لا تقرير",
  "Change Password": "تغيير كلمة المرور",
  "Vacation": "إجازة",
  "Personal reason": "سبب شخصي",
  "Queue": "قائمة الانتظار",
  "Completed": "مكتمل",
  "Cancelled": "ملغى",
  "Show attributes": "عرض السمات",
  "Edit attributes": "تعديل السمات",
  "Add attributes": "إضافة سمات",
  "Delete service": "حذف الخدمة",
  "Edit service": "تعديل الخدمة",
  "Create": "إنشاء",
  "Conversations": "المحادثات",
  "Search": "بحث",
  "Deposit Amount": "مبلغ الإيداع",
  "Enter deposit amount": "أدخل مبلغ الإيداع",
  "Deposit from current balance": "إيداع من الرصيد الحالي",
  "My services": "خدماتي",
  "Create Service": "إنشاء خدمة",
  "Is available to all cities and area": "متاح لجميع المدن والمناطق",
  "Category": "الفئة",
  "Sub category": "الفئة الفرعية",
  "Child category": "فئة الأطفال",
  "Select child category": "اختر فئة الأطفال",
  "Select Subcategory": "اختر الفئة الفرعية",
  "Select Category": "اختر الفئة",
  "Title": "العنوان",
  "Please enter a title": "يرجى إدخال عنوان",
  "Video URL": "رابط الفيديو",
  "Youtube embed code": "رمز تضمين يوتيوب",
  "Description": "الوصف",
  "Upload main image": "تحميل الصورة الرئيسية",
  "Upload gallery image": "تحميل صورة المعرض",
  "You must enter a title and description": "يجب عليك إدخال عنوان ووصف",
  "Description must be at least 150 characters": "يجب أن يكون الوصف لا يقل عن 150 حرفًا",
  "Next": "التالي",
  "Online service": "الخدمة عبر الإنترنت",
  "What is Included In This Package": "ما يتضمنه هذا العرض",
  "Enter title": "أدخل العنوان",
  "Price": "السعر",
  "Enter price": "أدخل السعر",
  "Please enter a price": "يرجى إدخال سعر",
  "Add Additional Services": "إضافة خدمات إضافية",
  "Unit price": "سعر الوحدة",
  "Quantity": "الكمية",
  "Enter quantity": "أدخل الكمية",
  "Please fill out all fields": "يرجى ملء جميع الحقول",
  "Benefit Of This Package": "فوائد هذه الحزمة",
  "Type here": "اكتب هنا",
  "Please type something first": "يرجى كتابة شيء أولاً",
  "Faqs": "الأسئلة الشائعة",
  "Faq title": "عنوان الأسئلة الشائعة",
  "Faq answer": "إجابة الأسئلة المتداولة",
  "Enter answer": "أدخل الإجابة",
  "Service attributes": "خصائص الخدمة",
  "Include Service Attributes": "تضمين خصائص الخدمة",
  "No include service found": "لم يتم العثور على خدمة مدرجة",
  "Additional Service Attributes ": "خصائص خدمة إضافية",
  "No additional service found": "لم يتم العثور على خدمة إضافية",
  "Service Benefit": "فائدة الخدمة",
  "No service benefit found": "لم يتم العثور على فائدة للخدمة",
  "Edit Service": "تعديل الخدمة",
  "Active": "نشط",
  "Pending": "قيد الانتظار",
  "pending": "قيد الانتظار",
  "Delivered": "تم التسليم",
  "complete": "مكتمل",
  "Unknown": "غير معروف",
  "hello": "مرحبا",
  "Skip": "تخطي",
  "Continue": "متابعة",
  "Delete": "حذف",
  "Cancel": "إلغاء",
  "Are you sure?": "هل أنت متأكد؟",
  "Are you sure": "هل أنت متأكد",
  "Schedules": "الجداول",
  "Create Day": "إنشاء يوم",
  "Days": "الأيام",
  "Choose day": "اختر اليوم",
  "Create Schedule": "إنشاء جدول",
  "eg: 10:00Am - 11:00PM, this schedule time will show in frontend, when anyone want to book your service, they will select this schedule time made by you":
      "مثال: 10:00 صباحًا - 11:00 مساءً، هذا الجدول الزمني سيظهر في الواجهة الأمامية، عندما يرغب أي شخص في حجز خدمتك، سيقومون باختيار هذا الوقت الذي حددته.",
  "No days found": "لم يتم العثور على أيام",
  "Add Day": "إضافة يوم",
  "Select a day to save": "اختر يومًا للحفظ",
  "Day created successfully": "تم إنشاء اليوم بنجاح",
  "Creating day failed": "فشل إنشاء اليوم",
  "Day fetching failed": "فشل جلب اليوم",
  "Request timeout": "انتهاء مهلة الطلب",
  "Fetching days failed": "فشل جلب الأيام",
  "Add this schedule time for all days.": "أضف هذا الوقت للجدول لجميع الأيام.",
  "Schedule fetching failed": "فشل جلب الجدول",
  "Next page loading failed": "فشل تحميل الصفحة التالية",
  "Select a day to continue": "اختر يومًا للاستمرار",
  "Write schedule to continue": "اكتب الجدول للاستمرار",
  "Creating schedule failed": "فشل إنشاء الجدول",
  "Schedule deleted successfully": "تم حذف الجدول بنجاح",
  "Schedule delete failed": "فشل حذف الجدول",
  "Deleting day failed": "فشل حذف اليوم",
  "Day deleted successfully": "تم حذف اليوم بنجاح",
  "No more Data": "لا توجد بيانات أخرى",
  "Release to load more": "افرج لتحميل المزيد",
  "Load Failed": "فشل التحميل",
  "Schedule updated successfully": "تم تحديث الجدول بنجاح",
  "Updating schedule failed": "فشل تحديث الجدول",
  "Schedule created successfully": "تم إنشاء الجدول بنجاح",
  "Update Schedule": "تحديث الجدول",
  "Sat": "السبت",
  "Sun": "الأحد",
  "Mon": "الإثنين",
  "Tue": "الثلاثاء",
  "Wed": "الأربعاء",
  "Fri": "الجمعة",
  "Thu": "الخميس",
  "Support tickets": "تذاكر الدعم",
  "Priority": "الأولوية",
  "Order number": "رقم الطلب",
  "Success": "نجاح",
  "Order extra accepted": "تم قبول الطلب الإضافي",
  "Hired successfully": "تم التوظيف بنجاح",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "Enter schedule": "أدخل الجدول",
  "Add Schedule": "إضافة جدول",
  "No schedules found": "لم يتم العثور على جداول",
  "May": "مايو",
  "Jun": "يونيو",
  "Jul": "يوليو",
  "Aug": "أغسطس",
  "Sep": "سبتمبر",
  "Oct": "أكتوبر",
  "Nov": "نوفمبر",
  "Dec": "ديسمبر",
  "Jan": "يناير",
  "Feb": "فبراير",
  "Mar": "مارس",
  "Apr": "أبريل",
  "What went wrong?": "ماذا حدث؟",
  "Write the issue": "اكتب المشكلة",
  "Submit Report": "تقديم التقرير",
  "You must write a report to submit": "يجب عليك كتابة تقرير لتقديمه",
  "Report": "تقرير",
  "Yes": "نعم",
  "Chat Payment details": "تفاصيل دفع الدردشة",
  "Please indicate your payment account": "يرجى تحديد حساب الدفع الخاص بك",
  "Urgent": "عاجل",
  "High": "مرتفع",
  "Half": "نصف",
  "Low": "منخفض",
  "open": "مفتوح",
  "Offer price": "سعر العرض",
  "Cover letter": "رسالة تقديم",
  "You must enter a valid price": "يجب عليك إدخال سعر صالح",
  "Search country": "ابحث عن بلد",
  "Please enter a quantity": "يرجى إدخال كمية",
  "Add": "إضافة",
  "requested to mark his order complete.": "طلب وضع علامة على طلبه كمكتمل.",
  "You can not change order status due to payment status pending.": "لا يمكنك تغيير حالة الطلب بسبب حالة الدفع المعلقة.",
  "Your request submitted. Buyer will complete your request after review.": "تم تقديم طلبك. سيقوم المشتري بإكمال طلبك بعد المراجعة.",
  "requested new extra service.": "طلب خدمة إضافية جديدة.",
  "has requested for extra service.": "طلب خدمة إضافية.",
  "You must enter a valid amount": "يجب عليك إدخال مبلغ صالح",
  "Quantity must be an integer value": "يجب أن تكون الكمية قيمة عددية صحيحة",
  "Please enter ticket title": "يرجى إدخال عنوان التذكرة",
  "Ticket title": "عنوان التذكرة",
  "Please explain your problem": "يرجى شرح مشكلتك",
  "Create ticket": "إنشاء تذكرة",
  "Please enter order id": "يرجى إدخال رقم الطلب",
  "Order Id": "رقم الطلب",
  "Edit": "تعديل",
  "Withdraw amount not less than": "سحب مبلغ لا يقل عن",
  "Payout request success": "نجاح طلب الدفع",
  "manual payment": "دفع يدوي",
  "Details": "التفاصيل",
  "Additional Service Attributes": "خصائص خدمة إضافية",
  "Enter a valid amount": "أدخل مبلغًا صالحًا",
  "No city found": "لم يتم العثور على مدينة",
  "Search state": "ابحث عن ولاية",
  "Select City": "اختر مدينة",
  "No country found": "لم يتم العثور على بلد",
  "No area found": "لم يتم العثور على منطقة",
  "Search area": "ابحث عن منطقة",
  "Choose image": "اختر صورة",
  "declined your order extra request": "رفض طلبك الإضافي",
  "Decline Success": "نجاح الرفض",
  "Extra Service Not Found": "الخدمة الإضافية غير موجودة",
  "No date found": "لم يتم العثور على تاريخ",
  "No Schedule Created": "لم يتم إنشاء جدول",
  "All jobs": "جميع الوظائف",
  "No jobs found": "لم يتم العثور على وظائف",
  "Please enter a valid password": "يرجى إدخال كلمة مرور صالحة",
  "Delete account": "حذف الحساب",
  "Invalid password": "كلمة مرور غير صالحة",
  "No payment history found": "لم يتم العثور على تاريخ المدفوعات",
  "active": "نشط",
  "delivered": "تم التسليم",
  "cancelled": "ملغى",
  "No order found": "لم يتم العثور على طلب",
  "Order Not Found": "الطلب غير موجود",
  "Support Ticket Created Success": "تم إنشاء تذكرة الدعم بنجاح",
  "Login successful": "تسجيل الدخول ناجح",
  "All": "الكل",
  "Create day to add schedule": "أنشئ يومًا لإضافة جدول",
  "Order": "طلب",
  "Message:": "رسالة:",
  "Your payment process will be terminated.": "ستُنهى عملية الدفع الخاصة بك.",
  "Payment cancelled!": "تم إلغاء الدفع!",
  "Payment failed!": "فشل الدفع!",
  "Payment has been expired.": "انتهت صلاحية الدفع.",
  "Payment has been cancelled.": "تم إلغاء الدفع.",
  "Cash on delivery is not available for subscription renew": "الدفع عند الاستلام غير متاح لتجديد الاشتراك",
  "Pay by wallet is not available for wallet deposit": "الدفع عبر المحفظة غير متاح لإيداع المحفظة",
  "Job id": "رقم الوظيفة",
  "Privacy policy": "سياسة الخصوصية",
  "Terms & Conditions": "الشروط والأحكام",
  "and": "و",
  "I agree to": "أوافق على",
  "Applied": "تم التقديم",
  "Job expired": "انتهت صلاحية الوظيفة",
  "Hired": "تم التوظيف",
  "Language": "اللغة",
  "English": "الإنجليزية",
  "Arabic": "العربية",
};
